### ISSUE TITLE
Connect Deprecated Errors on run

### ISSUE THREAD

**Issue by MeTe-30** [txomin-jimenez/node-twain#1]
Hi,
I installed dependencies by 'npm i' and tried to run app with 'node app.js', but i'm facing with these errors.
What do i have to do?

`connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules\express\node_modules\connect\lib\middleware\bodyParser.js:56:20`
`connect deprecated limit: Restrict request size at location of read node_modules\express\node_modules\connect\lib\middleware\multipart.js:86:15 `
`connect deprecated methodOverride: use method-override npm module instead express-app\server\server.coffee:40:19`

Thanks...

**Comment by txomin-jimenez** [comment]
Hi, thanks for your interest in the project. Code it's quite outdated, so it's using deprecated Express modules. 
It's now fixed with last commit [#0198a6a](https://github.com/txomin-jimenez/node-twain/commit/0198a6af5d167e6def9040c5b71c0725871e1050)
